"""delete filed user's gender

Revision ID: 3b089b4c7866
Revises: 51c0ebcf30e2
Create Date: 2018-08-14 09:34:05.982032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b089b4c7866'
down_revision = '51c0ebcf30e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', mysql.VARCHAR(length=2), nullable=True))
    # ### end Alembic commands ###
