"""colum password changed _password

Revision ID: 64dccb6ea3ed
Revises: 3b089b4c7866
Create Date: 2018-08-14 14:39:50.336659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64dccb6ea3ed'
down_revision = '3b089b4c7866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.String(length=50), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
