"""add column thumbs_url

Revision ID: 7bc4c76fdebf
Revises: 1a4b5d000fcd
Create Date: 2018-08-15 10:27:36.012352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bc4c76fdebf'
down_revision = '1a4b5d000fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumbs_url', sa.String(length=100), nullable=True))
    op.add_column('posts', sa.Column('uploads_url', sa.String(length=100), nullable=True))
    op.drop_column('posts', 'upload_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('upload_url', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('posts', 'uploads_url')
    op.drop_column('posts', 'thumbs_url')
    # ### end Alembic commands ###
